# Generated by Django 4.2.4 on 2023-08-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_id_urldetail_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncrementalNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.BigIntegerField(default=100000000000)),
            ],
        ),
        migrations.AlterField(
            model_name='urldetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
