# Generated by Django 4.2.4 on 2023-08-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_incrementalnumber_alter_urldetail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldetail',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
